"""
mesh_decorators.py – Class and method decorators for HOMER mesh evaluation.

Provides:

* :func:`wide_eval` – marks a method as "wide-evaluatable".
* :func:`expand_wide_evals` – class decorator that automatically generates
  ``*_in_every_element`` and ``*_ele_xi_pair`` variants for every
  ``@wide_eval`` method, plus backwards-compatibility aliases.
* :func:`depreciation` – wraps a function to emit a deprecation warning on
  call.
* Helper functions for generating and caching ``.pyi`` stub files alongside
  the decorated class (``_get_class_hash``, ``_write_pyi``, etc.).

The ``@expand_wide_evals`` decorator is applied to :class:`~HOMER.mesher.MeshField`
to automatically extend its API without boilerplate.
"""

import ast
import jax
import jax.numpy as jnp
import hashlib 
import inspect
from pathlib import Path
import logging
import traceback

def wide_eval(fn):
    fn._is_derived = True
    return fn

def depreciation(fn):
    def new_fn(*a, **kw):
        traceback.print_stack()
        logging.warning(f"This old naming order is depreciated, and may be removed in a future update")
        return(fn(*a, **kw))
    return new_fn

def make_iee(name):
    def iee(self, *a, fit_params=None, **kw): 
        """Evaluates the base function in every element of the mesh"""

        if fit_params is None:
            fit_params = self.optimisable_param_array
        new_fn = getattr(self, name)
        mapped = jax.vmap(
            lambda e: new_fn(e, *a, fit_params=fit_params, **kw), in_axes=0
        )(jnp.arange(len(self.elements)))
        return mapped.reshape(-1, *mapped.shape[2:])
    return iee

def make_ele_xi_pair(name):  
    def ele_xi_pair(self, eles, xis, *a, fit_params=None, **kw):
        """
        Evaluates the base function in pairs of ele_xi_lists
        """
        if fit_params is None:
            fit_params = self.optimisable_param_array
        new_fn = getattr(self, name)
        eval_e = jnp.atleast_1d(eles)
        eval_xi = jnp.atleast_2d(xis)
        out_sorted = jax.vmap( #vmap original over every (element, xi) pair in sorted order
            lambda single_e, single_xi: new_fn(single_e, single_xi, *a, fit_params=fit_params, **kw), (0, 0)
        )(eval_e, eval_xi).squeeze()
        return out_sorted

    return ele_xi_pair

def _get_class_hash(cls) -> str:
    sources = []
    for name, val in sorted(vars(cls).items()):
        if callable(val):
            try:
                sources.append(inspect.getsource(val))
            except OSError:
                pass
    return hashlib.md5("\n".join(sources).encode()).hexdigest()

def _extract_hash(pyi_path: Path) -> str | None:
    """Extract the hash comment from an existing .pyi file."""
    if not pyi_path.exists():
        return None
    first_line = pyi_path.read_text().splitlines()[0]
    if first_line.startswith("# hash:"):
        return first_line.removeprefix("# hash:").strip()
    return None

def _annotation_str(annotation) -> str:
    if annotation is inspect.Parameter.empty:
        return ""
    if isinstance(annotation, str):
        return annotation
    if hasattr(annotation, "__name__"):
        return annotation.__name__
    # handles generics like list[int], int | None, etc.
    return str(annotation)

def _extract_import_lines(source_file: Path) -> list[str]:
    """Extract top-level import statements from a Python source file."""
    try:
        source = source_file.read_text()
        tree = ast.parse(source)
        stmts = []
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                stmt = ast.get_source_segment(source, node)
                if stmt:
                    stmts.append(stmt)
        return stmts
    except (SyntaxError, OSError):
        return []

def _write_pyi(cls, pyi_path: Path, current_hash: str):
    """Write a .pyi stub file for the decorated class and all other top-level module symbols."""
    source_file = Path(inspect.getfile(cls))
    import_lines = _extract_import_lines(source_file)

    lines = [
        f"# hash: {current_hash}",
        "# Auto-generated by @expand_wide_evals — do not edit manually",
        "",
    ] + import_lines + [""]

    try:
        source = source_file.read_text()
        tree = ast.parse(source)
    except (SyntaxError, OSError):
        tree = None

    if tree is not None:
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.ClassDef):
                if node.name == cls.__name__:
                    # Use runtime introspection for the decorated class to capture generated methods
                    lines.append(f"class {cls.__name__}:")
                    for name, val in sorted(vars(cls).items()):
                        if callable(val):
                            try:
                                sig = inspect.signature(val)
                                lines.append(f"    def {name}{sig}: ...")
                            except (ValueError, TypeError):
                                lines.append(f"    def {name}(self, *args, **kwargs): ...")
                else:
                    # Use AST for all other classes
                    bases = [ast.unparse(b) for b in node.bases]
                    base_str = f"({', '.join(bases)})" if bases else ""
                    lines.append(f"class {node.name}{base_str}:")
                    methods = [n for n in ast.iter_child_nodes(node)
                               if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
                    if not methods:
                        lines.append("    ...")
                    else:
                        for method in methods:
                            args_str = ast.unparse(method.args)
                            ret = f" -> {ast.unparse(method.returns)}" if method.returns else ""
                            lines.append(f"    def {method.name}({args_str}){ret}: ...")
                lines.append("")
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                args_str = ast.unparse(node.args)
                ret = f" -> {ast.unparse(node.returns)}" if node.returns else ""
                lines.append(f"def {node.name}({args_str}){ret}: ...")
                lines.append("")
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and not target.id.startswith('_'):
                        lines.append(f"{target.id}: ...")
                        lines.append("")
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                if not node.target.id.startswith('_'):
                    ann_str = ast.unparse(node.annotation)
                    lines.append(f"{node.target.id}: {ann_str}")
                    lines.append("")
    else:
        # Fallback: write only the decorated class
        lines.append(f"class {cls.__name__}:")
        for name, val in sorted(vars(cls).items()):
            if callable(val):
                try:
                    sig = inspect.signature(val)
                    lines.append(f"    def {name}{sig}: ...")
                except (ValueError, TypeError):
                    lines.append(f"    def {name}(self, *args, **kwargs): ...")

    pyi_path.write_text("\n".join(lines))
    print(f"[expand_wide_evals] Updated {pyi_path}")

def expand_wide_evals(cls:"type[MeshField]"):
    """Iterates through the class definition, defining a range of methods to evaluate functions."""
    for name, val in list(vars(cls).items()):
        if callable(val) and getattr(val, '_is_derived', False):
            setattr(cls, f"{name}_in_every_element", make_iee(name))
            setattr(cls, f"{name}_ele_xi_pair", make_ele_xi_pair(name))

    # backwards compatibility for naming.
    cls.evaluate_ele_xi_pair_deriv_embeddings = depreciation(cls.evaluate_deriv_embeddings_ele_xi_pair)
    cls.evaluate_ele_xi_pair_embeddings = depreciation(cls.evaluate_embeddings_ele_xi_pair)
    cls.evaluate_ele_xi_pair_normals = depreciation(cls.evaluate_normals_ele_xi_pair)
    # cls.strain_tensor_in_ele_xi_pairs = depreciation(cls.strain_tensor_ele_xi_pair)
    # cls.strain_tensor_iee = depreciation(cls.strain_tensor_in_every_element)

    # --- Stub generation ---
    try:
        source_file = Path(inspect.getfile(cls))
        pyi_path = source_file.with_suffix(".pyi")  # inline stub, alongside the .py file
        current_hash = _get_class_hash(cls)
        stored_hash = _extract_hash(pyi_path)
        if current_hash != stored_hash:
            _write_pyi(cls, pyi_path, current_hash)
    except (TypeError, OSError):
        pass  # skip if source is unavailable (e.g. REPL, frozen)
    return cls
