import jax
import jax.numpy as jnp
import hashlib 
import inspect
from pathlib import Path
import logging
import traceback

def wide_eval(fn):
    fn._is_derived = True
    return fn

def depreciation(fn):
    def new_fn(*a, **kw):
        traceback.print_stack()
        logging.warning(f"This old naming order is depreciated, and may be removed in a future update")
        return(fn(*a, **kw))
    return new_fn

def make_iee(name):
    def iee(self, *a, fit_params=None, **kw): 
        """Evaluates the base function in every element of the mesh"""

        if fit_params is None:
            fit_params = self.optimisable_param_array
        new_fn = getattr(self, name)
        mapped = jax.vmap(
            lambda e: new_fn(e, *a, fit_params=fit_params, **kw), in_axes=0
        )(jnp.arange(len(self.elements)))
        return mapped.reshape(-1, *mapped.shape[2:])
    return iee

def make_ele_xi_pair(name):  
    def ele_xi_pair(self, eles, xis, *a, fit_params=None, **kw):
        """
        Evaluates the base function in pairs of ele_xi_lists
        """
        if fit_params is None:
            fit_params = self.optimisable_param_array
        new_fn = getattr(self, name)
        eval_e = jnp.atleast_1d(eles)
        eval_xi = jnp.atleast_2d(xis)
        out_sorted = jax.vmap( #vmap original over every (element, xi) pair in sorted order
            lambda single_e, single_xi: new_fn(single_e, single_xi, *a, fit_params=fit_params, **kw), (0, 0)
        )(eval_e, eval_xi).squeeze()
        return out_sorted

    return ele_xi_pair

def _get_class_hash(cls) -> str:
    sources = []
    for name, val in sorted(vars(cls).items()):
        if callable(val):
            try:
                sources.append(inspect.getsource(val))
            except OSError:
                pass
    return hashlib.md5("\n".join(sources).encode()).hexdigest()

def _extract_hash(pyi_path: Path) -> str | None:
    """Extract the hash comment from an existing .pyi file."""
    if not pyi_path.exists():
        return None
    first_line = pyi_path.read_text().splitlines()[0]
    if first_line.startswith("# hash:"):
        return first_line.removeprefix("# hash:").strip()
    return None

def _annotation_str(annotation) -> str:
    if annotation is inspect.Parameter.empty:
        return ""
    if isinstance(annotation, str):
        return annotation
    if hasattr(annotation, "__name__"):
        return annotation.__name__
    # handles generics like list[int], int | None, etc.
    return str(annotation)

def _write_pyi(cls, pyi_path: Path, current_hash: str):
    """Write a .pyi stub file for the derived methods."""
    lines = [
        f"# hash: {current_hash}",
        f"# Auto-generated by @expand_derived — do not edit manually",
        "",
        f"class {cls.__name__}:",
    ]
    
    for name, val in sorted(vars(cls).items()):
        if callable(val):
            sig = inspect.signature(val)
            # Return type for _safe wraps original return in None union
            ret = sig.return_annotation
            ret_str = f" -> {_annotation_str(ret)}" if ret is not inspect.Parameter.empty else ""
            lines.append(f"    def {name}{sig}{ret_str}: ...")
    
    pyi_path.write_text("\n".join(lines))
    print(f"[expand_derived] Updated {pyi_path}")

def expand_wide_evals(cls:"type[MeshField]"):
    """Iterates through the class definition, defining a range of methods to evaluate functions."""
    for name, val in list(vars(cls).items()):
        if callable(val) and getattr(val, '_is_derived', False):
            setattr(cls, f"{name}_in_every_element", make_iee(name))
            setattr(cls, f"{name}_ele_xi_pair", make_ele_xi_pair(name))

    # backwards compatibility for naming.
    cls.evaluate_ele_xi_pair_deriv_embeddings = depreciation(cls.evaluate_deriv_embeddings_ele_xi_pair)
    cls.evaluate_ele_xi_pair_embeddings = depreciation(cls.evaluate_embeddings_ele_xi_pair)
    cls.evaluate_ele_xi_pair_normals = depreciation(cls.evaluate_normals_ele_xi_pair)
    # cls.strain_tensor_in_ele_xi_pairs = depreciation(cls.strain_tensor_ele_xi_pair)
    # cls.strain_tensor_iee = depreciation(cls.strain_tensor_in_every_element)

    # --- Stub generation ---
    try:
        source_file = Path(inspect.getfile(cls))
        pyi_path = (source_file.parents[2]/'stubs'/source_file.name).with_suffix(".pyi")
        current_hash = _get_class_hash(cls)
        stored_hash = _extract_hash(pyi_path)
        if current_hash != stored_hash:
            _write_pyi(cls, pyi_path, current_hash)
    except (TypeError, OSError):
        pass  # skip if source is unavailable (e.g. REPL, frozen)
    return cls
